In [1]:
import torch

In [3]:
a = torch.Tensor([[1,2,3],[4,5,6]])

In [4]:
a.shape

torch.Size([2, 3])

In [5]:
b = a[1]

In [6]:
b.shape

torch.Size([3])

In [7]:
d = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
d.shape

torch.Size([3, 3])

In [9]:
b@d

tensor([66., 81., 96.])

In [15]:
torch.transpose(b,0,1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [14]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
b

tensor([4., 5., 6.])

In [17]:
b@b


tensor(77.)

In [18]:
torch.zeros(3)

tensor([0., 0., 0.])

In [19]:
torch.zeros(1)

tensor([0.])

In [20]:
torch.Tensor(1)

tensor([0.])